cleanup login script, change firewall example
git-svn-id: svn://svn.openwrt.org/openwrt/trunk/openwrt@881 3c298f89-4303-0410-b956-a3cf2f4a3e73

diff --git a/target/default/target_skeleton/bin/login b/target/default/target_skeleton/bin/login
--- a/target/default/target_skeleton/bin/login
+++ b/target/default/target_skeleton/bin/login
@@ -1,21 +1,20 @@
 #!/bin/sh
-[ "$FAILSAFE" = "true" ] && exec /bin/ash --login
+. /etc/sysconf 2>&-
 
-[ -f /etc/sysconf ] && . /etc/sysconf
-
-if [ "$BR2_SYSCONF_TELNET_FAILSAFE_ONLY" = "y" ]; then
-        if grep '^root:!' /etc/passwd > /dev/null 2>/dev/null; then
-                echo "You need to set a login password to protect your"
-                echo "Router from unauthorized access."
-                echo
-                echo "Use 'passwd' to set your password."
-                echo "telnet login will be disabled afterwards,"
-                echo "You can then login using SSH."
-                echo
-        else
-                echo "Login failed."
-                exit 0
-        fi
-fi
-
+[ "$FAILSAFE" != "true" ] &&
+[ "$BR2_SYSCONF_TELNET_FAILSAFE_ONLY" = "y" ] &&
+{
+  grep '^root:[^!]' /etc/passwd >&- 2>&- &&
+  {
+    echo "Login failed."
+    exit 0
+  } || {
+cat << EOF
+ === IMPORTANT ============================
+  Use 'passwd' to set your login password
+  this will disable telnet and enable SSH
+ ------------------------------------------
+EOF
+  }
+}
 exec /bin/ash --login
