hide some non-critical error messages; prevent newbie bug reports
SVN-Revision: 1028

diff --git a/openwrt/target/default/target_skeleton/bin/firstboot b/openwrt/target/default/target_skeleton/bin/firstboot
--- a/openwrt/target/default/target_skeleton/bin/firstboot
+++ b/openwrt/target/default/target_skeleton/bin/firstboot
@@ -1,6 +1,11 @@
 #!/bin/sh
 # $Id$
 
+mount | grep squashfs >&- || {
+	echo "You do not have a squashfs partition; aborting"
+	echo "(firstboot cannot be run on jffs2 based firmwares)"
+	return
+}
 
 [ -f "/tmp/.firstboot" ] && {
 	echo "firstboot is already running"
