openvpn: add proto handler openvpn
Redmine-patch-id: 1227
Signed-off-by: Florian Eckert <fe@dev.tdt.de>

diff --git a/package/network/services/openvpn/files/openvpn.init b/package/network/services/openvpn/files/openvpn.init
--- a/package/network/services/openvpn/files/openvpn.init
+++ b/package/network/services/openvpn/files/openvpn.init
@@ -7,6 +7,11 @@
 START=90
 STOP=10
 
+EXTRA_COMMANDS="prepare"
+EXTRA_HELP="\
+        prepare Build config from uci\
+"
+
 USE_PROCD=1
 PROG=/usr/sbin/openvpn
 
@@ -163,4 +168,55 @@ start_service() {
 
 service_triggers() {
 	procd_add_reload_trigger openvpn
+}
+
+LOG="logger -t openvpn-prepare -p"
+prepare() {
+	local s="$1"
+
+	[ -z "$s" ] && {
+		$LOG error "Config not specified"
+		exit 1
+	}
+
+	uci -q get openvpn.$s > /dev/null || {
+		$LOG error "Config $s not found"
+		exit 2
+	}
+
+	. /usr/share/openvpn/openvpn.options
+
+	config_load 'openvpn'
+	config_get enabled "$s" 'enabled' 0
+	config_get config "$s" 'config'
+
+	[ "$enabled" != 0 ] && {
+		$LOG warning "This config $s is enabled and is started by the openvpn service"
+		exit 3
+	}
+
+	if [ ! -z "$config" ]; then
+		readlink -f "$config"
+		[ "$?" -ne 0 ] && {
+			$LOG error "Config file '$config' does not exist"
+			exit 4
+		}
+		local name=${config##*/}
+		if [ "${name%%.*}" != "$s" ]; then
+			$LOG error "Pre generated config file name '${config}' is not equal to openvpn section name '$s'"
+			exit 5
+		else
+			$LOG notice "Using pre generated config $config"
+			exit 0
+		fi
+	fi
+
+	[ ! -d "/var/etc" ] && mkdir -p "/var/etc"
+	[ -f "/var/etc/openvpn-${s}.conf" ] && rm "/var/etc/openvpn-${s}.conf"
+
+	append_bools "$s" $OPENVPN_BOOLS
+	append_params "$s" $OPENVPN_PARAMS
+
+	$LOG notice "Config $s generated"
+	exit 0
 }
