mediatek/filogic: add Keenetic KN-3411 support
Specification:
 - MT7981 CPU using 2.4GHz and 5GHz WiFi (both AX)
 - 256MB RAM
 - 128MB SPI NAND
 - 3 LEDs (red, green, blue)
 - 1 button (reset)
 - 1 1Gbit ethernet port (integrated phy)

Serial Interface:
 - 3 Pins GND, RX, TX
 - Settings: 115200, 8N1

Notes:
 - The device supports dual boot mode
 - Factory bootloader does not support image with ubi (only kernel (fit) + squashfs is accepted)
 - Leds: green - status, red - 2.4 Ghz, blue - 5 Ghz
 - Second firmware partition (firmware_2) is used for rootfs_data and formated as ubi

Flash instruction:
The only way to flash OpenWrt image is to use tftp recovery mode in U-Boot:

1. Configure PC with static IP 192.168.1.2/24 and tftp server.
2. Rename "openwrt-mediatek-filogic-keenetic_kn-3411-squashfs-factory.bin"
   to "KN-3411_recovery.bin" and place it in tftp server directory.
3. Connect PC with ethernet port, press the reset button, power up
   the device and keep button pressed until status led start blinking.
4. Device will download file from server, write it to flash and reboot.

Signed-off-by: Maxim Anisimov <maxim.anisimov.ua@gmail.com>

diff --git a/target/linux/mediatek/filogic/base-files/lib/preinit/75_rootfs_prepare b/target/linux/mediatek/filogic/base-files/lib/preinit/75_rootfs_prepare
--- a/target/linux/mediatek/filogic/base-files/lib/preinit/75_rootfs_prepare
+++ b/target/linux/mediatek/filogic/base-files/lib/preinit/75_rootfs_prepare
@@ -21,6 +21,39 @@ rootfs_create() {
 
 rootfs_prepare() {
 	case $(board_name) in
+	keenetic,kn-3411)
+		local mtdnum ubidev ubivol
+
+		. /lib/upgrade/nand.sh
+
+		ubidev=$(nand_find_ubi ubi)
+		if [ ! "$ubidev" ]; then
+			mtdnum=$(find_mtd_index ubi)
+			if [ ! "$mtdnum" ]; then
+				echo "Can't find mtd partition ubi"
+				return 1
+			fi
+
+			ubiformat "/dev/mtd$mtdnum" -y
+			ubiattach -m "$mtdnum"
+
+			ubidev=$(nand_find_ubi ubi)
+			if [ ! "$ubidev" ]; then
+				echo "Can't attach mtd partition ubi"
+				return 1
+			fi
+		fi
+		if ! ubinfo "/dev/$ubidev" -N rootfs_data &>/dev/null; then
+			echo "Creating \"rootfs_data\" UBI volume"
+
+			ubimkvol "/dev/$ubidev" -N rootfs_data -m
+			ubivol=$(nand_find_volume "$ubidev" rootfs_data)
+			if [ ! "$ubivol" ]; then
+				echo "Can't find ubifs data volume"
+				return 1
+			fi
+		fi
+		;;
 	netgear,wax220)
 		if ! ubinfo /dev/ubi0 -N rootfs_data &>/dev/null; then
 			echo "Creating \"rootfs_data\" UBI volume"
