base-files: fix led script to skip missing triggers
this is based on http://patchwork.ozlabs.org/patch/424451/

Signed-off-by: John Crispin <blogic@openwrt.org>

SVN-Revision: 44087

diff --git a/package/base-files/files/etc/init.d/led b/package/base-files/files/etc/init.d/led
--- a/package/base-files/files/etc/init.d/led
+++ b/package/base-files/files/etc/init.d/led
@@ -40,7 +40,11 @@ load_led() {
 			[ $default -eq 1 ] ||
 				echo 0 >/sys/class/leds/${sysfs}/brightness
 		}
-		echo $trigger > /sys/class/leds/${sysfs}/trigger
+		echo $trigger > /sys/class/leds/${sysfs}/trigger 2> /dev/null
+		[ $? = 0 ] || {
+			echo >&2 "Skipping trigger '$trigger' for led '$name' due to missing kernel module"
+			return 1
+		}
 		case "$trigger" in
 		"netdev")
 			[ -n "$dev" ] && {
