base-files: upgrade: organize files into environment variables
Organize all the common files used for sysupgrade into environment variables
and organize common variables used for sysupgrade into one script source,
/lib/upgrade/common.sh

This improves code maintenance regarding sysupgrade,
and allows for packages, per-target files, and other downstream projects
to call on these sysupgrade files with a reliable variable
that remains static and easily accessible,
in case the files or other values are changed in the future.

Signed-off-by: Michael Pratt <mcpratt@pm.me>

diff --git a/package/base-files/files/sbin/sysupgrade b/package/base-files/files/sbin/sysupgrade
--- a/package/base-files/files/sbin/sysupgrade
+++ b/package/base-files/files/sbin/sysupgrade
@@ -2,6 +2,7 @@
 
 . /lib/functions.sh
 . /lib/functions/system.sh
+. /lib/upgrade/common.sh
 . /usr/share/libubox/jshn.sh
 
 # initialize defaults
@@ -53,11 +54,6 @@ while [ -n "$1" ]; do
 	shift;
 done
 
-export CONFFILES=/tmp/sysupgrade.conffiles
-export CONF_TAR=/tmp/sysupgrade.tgz
-export ETCBACKUP_DIR=/etc/backup
-export INSTALLED_PACKAGES=${ETCBACKUP_DIR}/installed_packages.txt
-
 IMAGE="$1"
 
 [ -z "$IMAGE" -a -z "$NEED_IMAGE" -a $CONF_BACKUP_LIST -eq 0 -o $HELP -gt 0 ] && {
@@ -86,7 +82,7 @@ upgrade-option:
 
 backup-command:
 	-b | --create-backup <file>
-	             create .tar.gz of files specified in sysupgrade.conf
+	             create .tar.gz of files specified in $UPGRADE_CONF
 	             then exit. Does not flash an image. If file is '-',
 	             i.e. stdout, verbosity is set to 0 (i.e. quiet).
 	-r | --restore-backup <file>
@@ -135,7 +131,7 @@ list_static_conffiles() {
 	local filter=$1
 
 	find $(sed -ne '/^[[:space:]]*$/d; /^#/d; p' \
-		/etc/sysupgrade.conf /lib/upgrade/keep.d/* 2>/dev/null) \
+		$UPGRADE_CONF ${KEEP_DIR}/* 2>/dev/null) \
 		\( -type f -o -type l \) $filter 2>/dev/null
 }
 
@@ -159,8 +155,7 @@ add_overlayfiles() {
 
 		list_conffiles | cut -f2 -d ' ' | sort -u > "$conffiles"
 
-		# backup files from /etc/sysupgrade.conf and /lib/upgrade/keep.d, but
-		# ignore those aready controlled by opkg conffiles
+		# ignore files already controlled by opkg conffiles
 		list_static_conffiles | sort -u |
 			grep -h -v -x -F -f $conffiles > "$keepfiles"
 
@@ -183,7 +178,7 @@ add_overlayfiles() {
 	# busybox grep bug when file is empty
 	[ -s "$packagesfiles" ] || echo > $packagesfiles
 
-	( cd /overlay/upper/; find .$SAVE_OVERLAY_PATH \( -type f -o -type l \) $find_filter | sed \
+	( cd ${OVERLAY_DIR}/; find .$SAVE_OVERLAY_PATH \( -type f -o -type l \) $find_filter | sed \
 		-e 's,^\.,,' \
 		-e '\,^/etc/board.json$,d' \
 		-e '\,/[^/]*-opkg$,d' \
@@ -198,8 +193,8 @@ add_overlayfiles() {
 }
 
 if [ $SAVE_OVERLAY = 1 ]; then
-	[ ! -d /overlay/upper/etc ] && {
-		echo "Cannot find '/overlay/upper/etc', required for '-c'" >&2
+	[ ! -d ${OVERLAY_DIR}/etc ] && {
+		echo "Cannot find '${OVERLAY_DIR}/etc', required for '-c'" >&2
 		exit 1
 	}
 	sysupgrade_init_conffiles="add_overlayfiles"
@@ -246,7 +241,7 @@ do_save_conffiles() {
 		# rom is used for pkgs in /rom, even if updated later
 		find /usr/lib/opkg/info -name "*.control" \( \
 			\( -exec test -f /rom/{} \; -exec echo {} rom \; \) -o \
-			\( -exec test -f /overlay/upper/{} \; -exec echo {} overlay \; \) -o \
+			\( -exec test -f ${OVERLAY_DIR}/{} \; -exec echo {} overlay \; \) -o \
 			\( -exec echo {} unknown \; \) \
 			\) | sed -e 's,.*/,,;s/\.control /\t/' > ${INSTALLED_PACKAGES}
 	fi
@@ -300,8 +295,8 @@ type platform_check_image >/dev/null 2>/dev/null || {
 case "$IMAGE" in
 	http://*|\
 	https://*)
-		wget -O/tmp/sysupgrade.img "$IMAGE" || exit 1
-		IMAGE=/tmp/sysupgrade.img
+		wget -O $IMAGE_FILE "$IMAGE" || exit 1
+		IMAGE=$IMAGE_FILE
 		;;
 esac
 
@@ -315,8 +310,8 @@ case "$IMAGE" in
 	/tmp/*)	;;
 	*)
 		v "Image not in /tmp, copying..."
-		cp -f "$IMAGE" /tmp/sysupgrade.img
-		IMAGE=/tmp/sysupgrade.img
+		cp -f "$IMAGE" $IMAGE_FILE
+		IMAGE=$IMAGE_FILE
 		;;
 esac
 
