realtek: Be more versatile in getting the MAC address
Most of the realtek targets get the MAC address/range pretty standard
places. The U-Boot environment or the U-Boot 'sys' environment. Instead
of trying to read directly from flash, get these things from variables
if possible. Only if this fails, we fall back to alternative means.

This also means that this is generic enough, to support most/all of our
switches, except the HP ones, which embed the MAC address weirdly in the
header.

This means that, we first try to get the MAC address from the
devicetree, potentially set by U-Boot.

Secondly, we check if we have the U-Boot env tools to ask both the
environments, which gives us a nice and clean way to get this data.

If this fails, we'll resolve to more aggressive methods by dumping the
data from the various flashes. We are more flexible in naming of the
second partition, which could be named either `env2` or `sysenv`. This
more aggressive method is also useful for initramfs mode, which usually
does not expose the environment. A little bit of a hack ;).

Finally, if we fail to get a valid MAC address, resort to a random MAC
address supplied by OpenWRT.

Signed-off-by: Olliver Schinagl <oliver@schinagl.nl>

diff --git a/target/linux/realtek/base-files/etc/board.d/02_network b/target/linux/realtek/base-files/etc/board.d/02_network
--- a/target/linux/realtek/base-files/etc/board.d/02_network
+++ b/target/linux/realtek/base-files/etc/board.d/02_network
@@ -17,6 +17,90 @@ ucidef_set_poe() {
 	json_select ..
 }
 
+parse_mac_addr()
+{
+	if ! macaddr_valid "${label_mac:-}"; then
+		label_mac="$(get_mac_label)"
+	fi
+
+	if [ -f '/etc/fw_env.config' ] && \
+	   command -v 'fw_printenv'; then
+		if ! macaddr_valid "${label_mac:-}" > '/dev/null'; then
+			label_mac="$(fw_printenv -n 'ethaddr')"
+		fi
+
+		if ! macaddr_valid "${lan_mac_start:-}" > '/dev/null'; then
+			lan_mac_start="$(fw_printenv -n 'mac_start')"
+		fi
+
+		if ! macaddr_valid "${lan_mac_end:-}" > '/dev/null'; then
+			lan_mac_end="$(fw_printenv -n 'mac_end')"
+		fi
+	fi
+
+	if [ -f '/etc/fw_sys.config' ] && \
+	   command -v 'fw_printsys'; then
+		if ! macaddr_valid "${label_mac:-}" > '/dev/null'; then
+			label_mac="$(fw_printsys -n 'ethaddr')"
+		fi
+
+		if ! macaddr_valid "${lan_mac_start:-}" > '/dev/null'; then
+			lan_mac_start="$(fw_printsys -n 'mac_start')"
+		fi
+
+		if ! macaddr_valid "${lan_mac_end:-}" > '/dev/null'; then
+			lan_mac_end="$(fw_printsys -n 'mac_end')"
+		fi
+	fi
+
+	if [ -n "$(find_mtd_index 'u-boot-env')" ]; then
+		if ! macaddr_valid "${label_mac:-}" > '/dev/null'; then
+			label_mac="$(mtd_get_mac_ascii 'u-boot-env' 'ethaddr')"
+		fi
+
+		if ! macaddr_valid "${lan_mac_start:-}" > '/dev/null'; then
+			lan_mac_start="$(mtd_get_mac_ascii 'u-boot-env' 'mac_start')"
+		fi
+
+		if ! macaddr_valid "${lan_mac_end:-}" > '/dev/null'; then
+			lan_mac_end="$(mtd_get_mac_ascii 'u-boot-env' 'mac_end')"
+		fi
+	fi
+
+	if [ -n "$(find_mtd_index 'u-boot-sysenv')" ]; then
+		if ! macaddr_valid "${label_mac:-}" > '/dev/null'; then
+			label_mac="$(mtd_get_mac_ascii 'u-boot-sysenv' 'ethaddr')"
+		fi
+
+		if ! macaddr_valid "${lan_mac_start:-}" > '/dev/null'; then
+			lan_mac_start="$(mtd_get_mac_ascii 'u-boot-sysenv' 'mac_start')"
+		fi
+
+		if ! macaddr_valid "${lan_mac_end:-}" > '/dev/null'; then
+			lan_mac_end="$(mtd_get_mac_ascii 'u-boot-sysenv' 'mac_end')"
+		fi
+	fi
+
+	if [ -n "$(find_mtd_index 'u-boot-env2')" ]; then
+		if ! macaddr_valid "${label_mac:-}" > '/dev/null'; then
+			label_mac="$(mtd_get_mac_ascii 'u-boot-env2' 'ethaddr')"
+		fi
+
+		if ! macaddr_valid "${lan_mac_start:-}" > '/dev/null'; then
+			lan_mac_start="$(mtd_get_mac_ascii 'u-boot-env2' 'mac_start')"
+		fi
+
+		if ! macaddr_valid "${lan_mac_end:-}" > '/dev/null'; then
+			lan_mac_end="$(mtd_get_mac_ascii 'u-boot-env2' 'mac_end')"
+		fi
+	fi
+
+	if ! macaddr_valid "${label_mac:-}" > '/dev/null'; then
+		echo 'Unable to find valid (label) MAC address, using random' >&2
+		label_mac="$(macaddr_random)"
+	fi
+}
+
 board=$(board_name)
 board_config_update
 
@@ -27,34 +111,28 @@ lan_list="$(for _port in ${port_list}; do printf "lan${_port} "; done)"
 ucidef_set_bridge_device
 ucidef_set_interface_lan "$lan_list"
 
-lan_mac=""
-lan_mac_start=""
-lan_mac_end=""
-label_mac=""
 case $board in
 hpe,1920-8g|\
 hpe,1920-16g|\
 hpe,1920-24g)
 	label_mac=$(mtd_get_mac_binary factory 0x68)
-	lan_mac=$label_mac
 	mac_count1=$(hexdump -v -n 4 -s 0x110 -e '4 "%d"' $(find_mtd_part factory) 2>/dev/null)
 	mac_count2=$(hexdump -v -n 4 -s 0x114 -e '4 "%d"' $(find_mtd_part factory) 2>/dev/null)
 	lan_mac_start=$(macaddr_add $lan_mac 2)
 	lan_mac_end=$(macaddr_add $lan_mac $((mac_count2-mac_count1)))
 	;;
-tplink,sg2008p-v1|\
-tplink,sg2210p-v3|\
-tplink,sg2452p-v4)
-	label_mac=$(get_mac_label)
-	lan_mac="$label_mac"
-	;;
 *)
-	lan_mac=$(mtd_get_mac_ascii u-boot-env2 mac_start)
-	lan_mac_end=$(mtd_get_mac_ascii u-boot-env2 mac_end)
-	label_mac=$(mtd_get_mac_ascii u-boot-env ethaddr)
-	[ -z "$lan_mac" ] && lan_mac=$label_mac
+	parse_mac_addr
 	;;
 esac
+
+# Cross copy MAC address variables, incorrect content will be caught after.
+if ! macaddr_valid "${label_mac:-}" > '/dev/null'; then
+	label_mac="${lan_mac_start:-}"
+fi
+if ! macaddr_valid "${lan_mac_start:-}" > '/dev/null'; then
+	lan_mac_start="${label_mac:-}"
+fi
 
 ucidef_set_interface_macaddr "lan" $lan_mac
 ucidef_set_bridge_mac "$lan_mac"
