base-files: /etc/profile service improvement
This patch introduces:

1. service enabled to list the status (enabled/disabled) of services in /etc/init.d
2. service <service-name-here> ubus to display the ubus call service list output for specified service

Signed-off-by: Stan Grishin <stangri@melmac.net>

diff --git a/package/base-files/files/etc/profile b/package/base-files/files/etc/profile
--- a/package/base-files/files/etc/profile
+++ b/package/base-files/files/etc/profile
@@ -50,10 +50,23 @@ EOF
 fi
 
 service() {
-	[ -f "/etc/init.d/$1" ] || {
-		echo "service "'"'"$1"'"'" not found, the following services are available:"
-		ls "/etc/init.d"
-		return 1
-	}
-	/etc/init.d/$@
+        if [ "$1" = "list-enabled" ]; then
+                for F in /etc/init.d/* ; do
+                        $F enabled && echo "$F enabled"
+                done;
+        elif [ "$1" = "list-disabled" ]; then
+                for F in /etc/init.d/* ; do
+                        $F enabled || echo "$F disabled"
+                done;
+        elif [ -f "/etc/init.d/$1" ]; then
+                /etc/init.d/$@
+        else
+                echo "Usage: service list-disabled|list-enabled|<service> [command]"
+                if [ -n "$1" ]; then
+                        echo "service "'"'"$1"'"'" not found, the following services are available:"
+                        ls "/etc/init.d"
+                fi
+                return 1
+        fi
 }
+
